# This file is generally only used for development
version: "3"
services:
    traefik:
        image: traefik
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
            - "80:80"
            - "8080:8080"
        command: --web --docker

    general_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "81:80"
        command: ./__main__.py --type general
        labels:
            - "traefik.frontend.rule=Host:general.localhost"
        depends_on:
            - pipeline

    music_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "82:80"
        command: ./__main__.py --type music
        labels:
            - "traefik.frontend.rule=Host:music.localhost"
        depends_on:
            - pipeline

    video_code:
        # Set CURRENT_ID by running CURRENT_UID=$(id -u):$(id -g) docker-compose up
        user: ${CURRENT_UID}
        build:
            context: .
            dockerfile: Dockerfile-vas
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "83:80"

        command: ./__main__.py --type video
        labels:
            - "traefik.frontend.rule=Host:video.localhost"
        depends_on:
            - pipeline

    pipeline:
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        command: celery -A tasks worker --loglevel=info
        depends_on:
            - broker
            - mongodb
            - backend
            - sqldb

    flower:
        user: ${CURRENT_UID}
        build: .
        restart: always
        volumes:
            - ./src:/code
        ports:
            - "84:80"
        command: flower -A tasks --port=80
        labels:
            - "traefik.frontend.rule=Host:monitor.localhost"
        depends_on:
            - pipeline

    broker:
        image: rabbitmq
        hostname: broker
        restart: always
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq

    backend:
        image: redis
        restart: always
        volumes:
            - ./redis:/data

    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass

    sqldb:
        image: postgres
        restart: always
        volumes:
            - ./postgres:/var/lib/postgresql
        environment:
            POSTGRES_DB: itumir
            POSTGRES_PASSWORD: pass
